name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  # 1. Build & Push
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ secrets.GHCR_USERNAME }}/crypto-test:${{ github.sha }}
            ghcr.io/${{ secrets.GHCR_USERNAME }}/crypto-test:latest

  # 2. Tests
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run frontend tests
        run: |
          docker run --rm ghcr.io/${{ secrets.GHCR_USERNAME }}/crypto-test:${{ github.sha }} npm test
